name: "Minor change"

on: 
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  increase-minor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: "Bump backend minor"
        working-directory: ./backend 
        run: npm version minor 
      - name: Commit changes
        working-directory: ./backend
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push

